[build]
  publish = ".output/public"
  command = "NITRO_PRESET=netlify npm run build && echo 'Build completed' && find .output -type d -name 'public' -exec ls -la {} \\;"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
